services:
  app:
    image: ghcr.io/oskarbarcz/flight-position-api
    build:
      context: .
      target: development
    env_file:
      - .env
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - '8080:3000'
    healthcheck:
      test: 'curl --fail http://localhost:3000 || exit 1'
      interval: 1s
      retries: 20
      start_period: 5s
      timeout: 1s
